import { AmbientLight, Color, DirectionalLight, PerspectiveCamera, Scene, TextureLoader, Vector3, WebGLRenderer } from "three";
import tileFacesUrl from "./assets/tiles/riichi-faces.webp?url";
import { ThreeTileFactory } from "./render/three-tile-factory.js";
const scene = new Scene(); scene.background = new Color("#073a29");
const camera = new PerspectiveCamera(28, innerWidth / innerHeight, 0.1, 100); camera.position.set(2.5, -2.5, 10); camera.lookAt(new Vector3(0, 0, 0));
const renderer = new WebGLRenderer({ antialias: true }); renderer.setPixelRatio(devicePixelRatio); renderer.setSize(innerWidth, innerHeight); document.body.append(renderer.domElement);
scene.add(new AmbientLight("#ffffff", 2)); const key = new DirectionalLight("#fff4d5", 2.2); key.position.set(-2, 3, 5); scene.add(key);
const factory = new ThreeTileFactory(await new TextureLoader().loadAsync(tileFacesUrl));
const ordinary = factory.create({ type: 1 }); ordinary.position.x = -1.2; scene.add(ordinary);
const dora = factory.create({ type: 1, dora: true }); dora.position.x = 1.2; scene.add(dora);
factory.setDoraGlowIntensity(Number(new URLSearchParams(location.search).get("intensity") ?? 1)); renderer.render(scene, camera);
