import { createIcons, Eye, EyeOff, RotateCcw, Vote } from "lucide";
import { createPlayweftClient } from "../../src/playweft-client.js";
import { startSoloDealer } from "./solo.js";
import { PRESETS, addCustomGod, clonePreset, normalizedConfig, roleCount } from "./role-config.js";
import "../../src/base.css";
import "./styles.css";
import "./solo.css";

const elements={root:document.querySelector(".dealer-layout"),connection:document.querySelector("#connection"),kicker:document.querySelector("#round-kicker"),heading:document.querySelector("#round-heading"),message:document.querySelector("#round-message"),roleCard:document.querySelector("#role-card"),roleEmblem:document.querySelector("#role-emblem"),roleName:document.querySelector("#role-name"),roleCopy:document.querySelector("#role-copy"),roleReveal:document.querySelector("#role-reveal"),voteRound:document.querySelector("#vote-round"),activeCount:document.querySelector("#active-count"),playerField:document.querySelector("#player-field"),voteProgress:document.querySelector("#vote-progress"),redeal:document.querySelector("#redeal-button"),flipHeading:document.querySelector("#flip-heading"),flipLog:document.querySelector("#flip-log")};
let playerId,state,pendingActionId,visibleRound;let roleVisible=false,playMode="room",soloStarted=false,roomDraft;
const preview={players:Array.from({length:6},(_,i)=>`preview-${i}`),roles:{},status:{},votes:{},flips:[],round:1,voteRound:1,lastEvent:{kind:"setup"}};
const isStandalone=window.parent===window;
const client=isStandalone?undefined:createPlayweftClient({onReady(message){playMode=message.mode??"room";if(playMode==="solo")return startSolo();playerId=message.playerId;setConnection("waiting","房间已连接");},onState(message){if(playMode==="solo")return;playerId=message.playerId;state=message.state;setConnection("live",state.phase==="setup"?"等待发牌":"实时房间");render(state);},onActionResult(result){if(playMode==="solo"||result.requestId!==pendingActionId)return;pendingActionId=undefined;render(state??preview);},onError(error,_code,requestId){if(requestId===pendingActionId)pendingActionId=undefined;setConnection("error","操作失败");elements.message.textContent=error;render(state??preview);}});
elements.roleReveal.addEventListener("click",()=>{if(!state||!state.roles?.[playerId])return;roleVisible=!roleVisible;render(state);});
elements.redeal.addEventListener("click",()=>send({type:"rematch"}));window.addEventListener("pagehide",()=>client?.destroy());if(isStandalone)startSolo();else render(preview);
function startSolo(){if(soloStarted)return;soloStarted=true;playMode="solo";startSoloDealer({root:elements.root,setConnection});}
function send(action){if(pendingActionId||!state||playMode!=="room")return false;const id=client?.sendAction(action);if(!id){elements.message.textContent="尚未连接 Playweft 平台";return false}pendingActionId=id;render(state);return true}
function render(next){if(playMode==="solo")return;if(next.phase==="setup")return renderRoomSetup(next);const players=next.players??[],ownIndex=players.indexOf(playerId),ownRole=next.roles?.[playerId],active=players.filter(id=>next.status?.[id]==="alive"),ownAlive=next.status?.[playerId]==="alive",votedFor=next.votes?.[playerId];if(visibleRound!==next.round){visibleRound=next.round;roleVisible=false}elements.voteRound.textContent=String(next.voteRound??1);elements.activeCount.textContent=`${active.length} 在场`;renderOwnRole(ownRole,Boolean(state));renderPlayers(next,players,ownIndex,ownAlive,votedFor,Boolean(state));renderFlips(next,players);elements.redeal.hidden=false;elements.redeal.disabled=!state||!!pendingActionId||ownIndex<0;const votes=active.filter(id=>next.votes?.[id]).length;elements.voteProgress.textContent=`${next.config?.name??"当前版型"} · 已投 ${votes} / ${active.length}`;if(state)renderStatus(next,players,ownIndex,active.length,votedFor)}
function renderRoomSetup(next){const count=next.players?.length??0;elements.kicker.textContent="发牌前配置";elements.heading.textContent=next.canConfigure?"选择版型与身份池":"等待房主配置版型";elements.message.textContent=next.canConfigure?`本房间 ${count} 人，身份池必须正好 ${count} 张。`:"房主确认版型后会自动洗牌并分配身份。";elements.voteRound.textContent="–";elements.activeCount.textContent=`${count} 人`;elements.redeal.hidden=true;elements.roleCard.dataset.role="hidden";elements.roleEmblem.textContent="?";elements.roleName.textContent="尚未发牌";elements.roleCopy.textContent="发牌前不会生成任何玩家身份";elements.roleReveal.disabled=true;elements.flipHeading.textContent="版型规则";elements.flipLog.innerHTML=next.canConfigure?'<p class="empty-flips">可选择预设、调整身份数量或添加自定义神职。</p>':'<p class="empty-flips">等待房主确认。</p>';if(!next.canConfigure){elements.playerField.innerHTML='<div class="room-config-waiting">房主正在配置身份池…</div>';elements.voteProgress.textContent="身份尚未生成";return}roomDraft??=clonePreset();renderRoomEditor(count)}
function renderRoomEditor(count){elements.playerField.innerHTML=`<div class="room-role-config"><label>默认版型<select id="room-preset">${PRESETS.map(p=>`<option value="${p.id}" ${p.id===roomDraft.presetId?"selected":""}>${p.name}</option>`).join("")}<option value="custom" ${roomDraft.presetId==="custom"?"selected":""}>自定义</option></select></label><div id="room-role-list" class="solo-role-list">${roomDraft.roles.map((r,i)=>roleRow(r,i)).join("")}</div><button id="room-add-role" class="solo-secondary-action" type="button">＋ 添加自定义神职</button><label>版型规则介绍（可选）<textarea id="room-rules" rows="4" maxlength="1000">${escapeHtml(roomDraft.rules)}</textarea></label><p id="room-config-feedback">身份池 ${roleCount(roomDraft)} / ${count} 张</p><button id="room-deal" class="solo-primary-action" type="button">确认版型并发牌</button></div>`;const list=document.querySelector("#room-role-list"),feedback=document.querySelector("#room-config-feedback");const read=()=>{roomDraft.roles=[...list.querySelectorAll("[data-role-row]")].map(row=>({id:row.dataset.roleId,name:row.querySelector("[data-role-name]").value,mark:row.querySelector("[data-role-name]").value.slice(0,1),team:row.dataset.team,copy:row.dataset.copy,count:Number(row.querySelector("[data-role-count]").value)}));roomDraft.rules=document.querySelector("#room-rules").value;roomDraft.presetId="custom";feedback.textContent=`身份池 ${roleCount(roomDraft)} / ${count} 张`};list.addEventListener("input",read);list.addEventListener("click",e=>{const b=e.target.closest("[data-remove-role]");if(!b)return;read();roomDraft.roles.splice(Number(b.dataset.removeRole),1);renderRoomEditor(count)});document.querySelector("#room-preset").addEventListener("change",e=>{if(e.target.value!=="custom")roomDraft=clonePreset(e.target.value);renderRoomEditor(count)});document.querySelector("#room-add-role").addEventListener("click",()=>{read();addCustomGod(roomDraft);renderRoomEditor(count)});document.querySelector("#room-deal").addEventListener("click",()=>{read();const config=normalizedConfig(roomDraft);if(roleCount(config)!==count){feedback.textContent=`身份池必须正好 ${count} 张，当前为 ${roleCount(config)} 张。`;return}send({type:"deal",config})});elements.voteProgress.textContent=`身份池 ${roleCount(roomDraft)} / ${count} 张`}
function roleRow(r,i){return`<div class="solo-role-row" data-role-row data-role-id="${escapeHtml(r.id)}" data-team="${escapeHtml(r.team)}" data-copy="${escapeHtml(r.copy)}"><input data-role-name value="${escapeHtml(r.name)}"><input data-role-count type="number" min="0" max="12" value="${r.count}"><button type="button" data-remove-role="${i}">×</button></div>`}
function detail(role){if(!role)return undefined;if(typeof role==="string")return{id:role,name:role,mark:"?",copy:""};return role}
function renderOwnRole(role,live){const d=roleVisible?detail(role):undefined;elements.roleCard.dataset.role=d?.id??"hidden";elements.roleEmblem.textContent=d?.mark??"?";elements.roleName.textContent=d?.name??(live?"身份未翻开":"等待发牌");elements.roleCopy.textContent=d?.copy??state?.config?.rules??"开局后由你自己翻开身份牌";elements.roleReveal.disabled=!live||!role||!!pendingActionId;elements.roleReveal.innerHTML=roleVisible?'<span class="icon-button-content"><i data-lucide="eye-off"></i><span>盖回身份</span></span>':'<span class="icon-button-content"><i data-lucide="eye"></i><span>查看身份</span></span>';createIcons({icons:{Eye,EyeOff,RotateCcw,Vote}})}
function renderPlayers(next,players,ownIndex,ownAlive,votedFor,live){const active=players.filter(id=>next.status?.[id]==="alive");elements.playerField.innerHTML=active.map(id=>{const i=players.indexOf(id),self=i===ownIndex,selected=votedFor===id,canVote=live&&ownAlive&&!pendingActionId;return`<article class="player-seat${self?" is-self":""}${selected?" is-selected":""}"><div class="seat-number">${i+1}</div><div class="seat-copy"><strong>${self?"你":`玩家 ${i+1}`}</strong><span>${next.votes?.[id]?"已投票":"等待投票"}</span></div><button class="vote-action" data-target="${id}" ${canVote?"":"disabled"}><i data-lucide="vote"></i><span>${selected?"已投":"投票"}</span></button></article>`}).join("");elements.playerField.querySelectorAll("[data-target]").forEach(b=>b.addEventListener("click",()=>send({type:"vote",target:b.dataset.target})));createIcons({icons:{Eye,EyeOff,RotateCcw,Vote}})}
function renderFlips(next,players){const flips=next.flips??[];elements.flipHeading.textContent=flips.length?`已翻 ${flips.length} 张身份牌`:"尚无人出局";elements.flipLog.innerHTML=flips.length?flips.map(f=>{const d=detail(f.role);return`<article class="flip-entry"><span class="flip-mark">${escapeHtml(d?.mark??"?")}</span><div><strong>${playerLabel(players,f.player)} · ${escapeHtml(d?.name??"未知身份")}</strong><p>已翻牌并离场。</p></div></article>`}).join(""):'<p class="empty-flips">投票结算后，出局玩家的身份会显示在这里。</p>'}
function renderStatus(next,players,ownIndex,activeCount,votedFor){const e=next.lastEvent??{},player=e.player?playerLabel(players,e.player):"";if(ownIndex<0){elements.kicker.textContent="观战中";elements.heading.textContent=`${activeCount} 位玩家仍在场`;return}if(next.status?.[playerId]!=="alive"){elements.kicker.textContent="已离场";elements.heading.textContent="等待本局其余投票";return}if(e.kind==="eliminated"){elements.kicker.textContent="翻牌结算";elements.heading.textContent=`${player} 是${detail(e.role)?.name??"未知身份"}`;elements.message.textContent="下一轮投票已经开始。";return}if(e.kind==="tied"){elements.kicker.textContent="平票";elements.heading.textContent="无人出局，重新投票";return}elements.kicker.textContent=`第 ${next.round} 局 · ${next.config?.name??"狼人杀"}`;elements.heading.textContent=votedFor?"你的票已提交":"请选择本轮投票目标";elements.message.textContent=next.config?.rules||"全部在场玩家投票后，系统自动结算并翻牌。"}
function playerLabel(players,id){const i=players.indexOf(id);return i>=0?`玩家 ${i+1}`:"玩家"}function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function setConnection(mode,label){elements.connection.dataset.mode=mode;elements.connection.querySelector("span").textContent=label}
